### ISSUE TITLE
About the 2D bouding box.

### ISSUE THREAD

**Issue by albertcity** [aistairc/virtualhome_aist#23]
Hi,
I am developing over virtualhome_aist to generate data for VLM training. I have found that in the README.md it is said `The 2D bounding boxes of objects can now be output`, however I can not find any example code to produce the 2D bbox (per frame). Could you help me please?

**Comment by Ease112** [comment]
Hi,
The following parameters must be specified in `render_script()`.
```
vis_check_object=True, 
vis_check_character=True,
vis_check_object_all=True,
```
The following notebook may help you.
https://github.com/aistairc/virtualhome_aist/blob/main/demo/scenario_generate_graph_and_video_with_cameras_changes.ipynb

The specification of the original render_script() is here:
http://virtual-home.org/documentation/master/api/interaction.html?highlight=render_script#unity_simulator.UnityCommunication.render_script

The above three parameters were newly introduced in VirtualHome-AIST.
